package webService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-12-12T14:42:21.449-04:30
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "ServicioWebTriajeService", 
                  wsdlLocation = "docs/servicioWebTriaje1.wsdl",
                  targetNamespace = "http://webService/") 
public class ServicioWebTriajeService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webService/", "ServicioWebTriajeService");
    public final static QName ServicioWebTriajeServicePort = new QName("http://webService/", "ServicioWebTriajeServicePort");
    static {
        URL url = ServicioWebTriajeService.class.getResource("docs/servicioWebTriaje1.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(ServicioWebTriajeService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "docs/servicioWebTriaje1.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public ServicioWebTriajeService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServicioWebTriajeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioWebTriajeService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServicioWebTriajeService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServicioWebTriajeService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServicioWebTriajeService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ServicioWebTriajeServicePortType
     */
    @WebEndpoint(name = "ServicioWebTriajeServicePort")
    public ServicioWebTriajeServicePortType getServicioWebTriajeServicePort() {
        return super.getPort(ServicioWebTriajeServicePort, ServicioWebTriajeServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioWebTriajeServicePortType
     */
    @WebEndpoint(name = "ServicioWebTriajeServicePort")
    public ServicioWebTriajeServicePortType getServicioWebTriajeServicePort(WebServiceFeature... features) {
        return super.getPort(ServicioWebTriajeServicePort, ServicioWebTriajeServicePortType.class, features);
    }

}
