package webService;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-12-11T10:12:55.885-04:30
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://webService/", name = "ServicioWebTriajeServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ServicioWebTriajeServicePortType {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "serviceHolaMundo", targetNamespace = "http://webService/", className = "webService.ServiceHolaMundo")
    @WebMethod
    @ResponseWrapper(localName = "serviceHolaMundoResponse", targetNamespace = "http://webService/", className = "webService.ServiceHolaMundoResponse")
    public webService.PojoPrueba serviceHolaMundo();
}
