package webService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-12-14T11:34:48.675-04:30
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://webService/", name = "ServicioWebTriajeServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ServicioWebTriajeServicePortType {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getStatusCaso", targetNamespace = "http://webService/", className = "webService.GetStatusCaso")
    @WebMethod
    @ResponseWrapper(localName = "getStatusCasoResponse", targetNamespace = "http://webService/", className = "webService.GetStatusCasoResponse")
    public java.lang.String getStatusCaso(
        @WebParam(name = "uuid", targetNamespace = "")
        java.lang.String uuid
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "enviarCasoTriaje", targetNamespace = "http://webService/", className = "webService.EnviarCasoTriaje")
    @WebMethod
    @ResponseWrapper(localName = "enviarCasoTriajeResponse", targetNamespace = "http://webService/", className = "webService.EnviarCasoTriajeResponse")
    public boolean enviarCasoTriaje(
        @WebParam(name = "caso", targetNamespace = "")
        webService.PojoCaso caso,
        @WebParam(name = "uuid", targetNamespace = "")
        java.lang.String uuid
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCasoResuelto", targetNamespace = "http://webService/", className = "webService.GetCasoResuelto")
    @WebMethod
    @ResponseWrapper(localName = "getCasoResueltoResponse", targetNamespace = "http://webService/", className = "webService.GetCasoResueltoResponse")
    public webService.PojoCasoResuelto getCasoResuelto(
        @WebParam(name = "caso", targetNamespace = "")
        webService.PojoCaso caso
    );
}
