package webService;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-12-10T14:41:10.390Z
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://webService/", name = "TriajeServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface TriajeServicePortType {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "serviceHolaMundo", targetNamespace = "http://webService/", className = "webService.ServiceHolaMundo")
    @WebMethod
    @ResponseWrapper(localName = "serviceHolaMundoResponse", targetNamespace = "http://webService/", className = "webService.ServiceHolaMundoResponse")
    public webService.PojoPrueba serviceHolaMundo();
}
