package imp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.4
 * 2012-02-23T21:39:53.708-04:30
 * Generated source version: 2.4.4
 * 
 */
@WebServiceClient(name = "ImpService", 
                  wsdlLocation = "docs/imp.wsdl",
                  targetNamespace = "http://imp/") 
public class ImpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://imp/", "ImpService");
    public final static QName ImpServicePort = new QName("http://imp/", "ImpServicePort");
    static {
        URL url = null;
        try {
            url = new URL("docs/imp.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ImpService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "docs/imp.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ImpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ImpService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ImpServicePortType
     */
    @WebEndpoint(name = "ImpServicePort")
    public ImpServicePortType getImpServicePort() {
        return super.getPort(ImpServicePort, ImpServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ImpServicePortType
     */
    @WebEndpoint(name = "ImpServicePort")
    public ImpServicePortType getImpServicePort(WebServiceFeature... features) {
        return super.getPort(ImpServicePort, ImpServicePortType.class, features);
    }

}
