package imp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-12-11T10:12:55.760-04:30
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "ImpService", 
                  wsdlLocation = "docs/imp.wsdl",
                  targetNamespace = "http://imp/") 
public class ImpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://imp/", "ImpService");
    public final static QName ImpServicePort = new QName("http://imp/", "ImpServicePort");
    static {
        URL url = ImpService.class.getResource("docs/imp.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(ImpService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "docs/imp.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public ImpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ImpService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ImpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ImpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ImpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ImpServicePortType
     */
    @WebEndpoint(name = "ImpServicePort")
    public ImpServicePortType getImpServicePort() {
        return super.getPort(ImpServicePort, ImpServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ImpServicePortType
     */
    @WebEndpoint(name = "ImpServicePort")
    public ImpServicePortType getImpServicePort(WebServiceFeature... features) {
        return super.getPort(ImpServicePort, ImpServicePortType.class, features);
    }

}
