
package org.opensih.webservices;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Tue Dec 15 16:04:03 GMT 2009
 * Generated source version: 2.2.3
 * 
 */

public final class OpenSIH_0020_0020Prototipo_0020WebService_0020Publisher_OpenSIH_0020_0020Prototipo_0020WebService_0020PublisherPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservices.opensih.org/", "ConsultaRepo");

    private OpenSIH_0020_0020Prototipo_0020WebService_0020Publisher_OpenSIH_0020_0020Prototipo_0020WebService_0020PublisherPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = ConsultaRepo.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ConsultaRepo ss = new ConsultaRepo(wsdlURL, SERVICE_NAME);
        OpenSIH_0020_0020Prototipo_0020WebService_0020Publisher port = ss.getOpenSIH_0020_0020Prototipo_0020WebService_0020PublisherPort();  
        
        {
        System.out.println("Invoking pdqSupplierQUQIIN000003UV01Cancel...");
        java.lang.String _pdqSupplierQUQIIN000003UV01Cancel_arg0 = "";
        port.pdqSupplierQUQIIN000003UV01Cancel(_pdqSupplierQUQIIN000003UV01Cancel_arg0);


        }
        {
        System.out.println("Invoking pdqSupplierPRPAIN201305UV...");
        java.lang.String _pdqSupplierPRPAIN201305UV_arg0 = "";
        java.lang.String _pdqSupplierPRPAIN201305UV__return = port.pdqSupplierPRPAIN201305UV(_pdqSupplierPRPAIN201305UV_arg0);
        System.out.println("pdqSupplierPRPAIN201305UV.result=" + _pdqSupplierPRPAIN201305UV__return);


        }
        {
        System.out.println("Invoking consultaPaciente...");
        java.lang.String _consultaPaciente_arg0 = "";
        java.lang.String _consultaPaciente__return = port.consultaPaciente(_consultaPaciente_arg0);
        System.out.println("consultaPaciente.result=" + _consultaPaciente__return);


        }
        {
        System.out.println("Invoking pixManagerPRPAIN201304UV02...");
        java.lang.String _pixManagerPRPAIN201304UV02_arg0 = "";
        port.pixManagerPRPAIN201304UV02(_pixManagerPRPAIN201304UV02_arg0);


        }
        {
        System.out.println("Invoking pdqSupplierQUQIIN000003UV01Continue...");
        java.lang.String _pdqSupplierQUQIIN000003UV01Continue_arg0 = "";
        java.lang.String _pdqSupplierQUQIIN000003UV01Continue__return = port.pdqSupplierQUQIIN000003UV01Continue(_pdqSupplierQUQIIN000003UV01Continue_arg0);
        System.out.println("pdqSupplierQUQIIN000003UV01Continue.result=" + _pdqSupplierQUQIIN000003UV01Continue__return);


        }
        {
        System.out.println("Invoking pixManagerPRPAIN201302UV02...");
        java.lang.String _pixManagerPRPAIN201302UV02_arg0 = "";
        port.pixManagerPRPAIN201302UV02(_pixManagerPRPAIN201302UV02_arg0);


        }
        {
        System.out.println("Invoking altaPaciente...");
        java.lang.String _altaPaciente_arg0 = "";
        java.lang.String _altaPaciente__return = port.altaPaciente(_altaPaciente_arg0);
        System.out.println("altaPaciente.result=" + _altaPaciente__return);


        }

        System.exit(0);
    }

}
