package cda;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.4
 * 2011-11-30T02:43:15.465-04:30
 * Generated source version: 2.4.4
 * 
 */
@WebService(targetNamespace = "http://cda/", name = "SecureServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface SecureServicePortType {

    @WebResult(name = "return", targetNamespace = "http://cda/")
    @RequestWrapper(localName = "secureMethod", targetNamespace = "http://cda/", className = "cda.SecureMethod")
    @WebMethod
    @ResponseWrapper(localName = "secureMethodResponse", targetNamespace = "http://cda/", className = "cda.SecureMethodResponse")
    public boolean secureMethod();
}
